ProductsModule/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ProductsModule.Data;
using ProductsModule.Models;

namespace ProductsModule.Controllers
{
	public class CategoryController : Controller
	{
		private readonly AppDbContext _db;
		public CategoryController(AppDbContext db)
		{
			_db = db;
		}
		public IActionResult Index()
		{
			List<Category> objCategoryList = _db.Categories.Where(b=>!b.IsDeleted).ToList();
			return View(objCategoryList);
		}

		//GET
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Category obj)
		{
			if (ModelState.IsValid)
			{
				_db.Categories.Add(obj);
				_db.SaveChanges();
				TempData["success"] = "(Category successfully created!)";
				return RedirectToAction("Index");
			}

			foreach (var modelState in ModelState.Values)
			{
				foreach (var error in modelState.Errors)
				{
					Console.WriteLine(error.ErrorMessage);
				}
			}
			return View();

		}

		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			Category? categoryFromDb = _db.Categories.FirstOrDefault(x => x.CategoryId == id);
			if (categoryFromDb == null)
			{
				return NotFound();
			}

			return View(categoryFromDb);
		}

		
		[HttpPost]
		[ActionName("Delete")]
		public IActionResult DeletePOST(int? id)
		{
			Category? obj = _db.Categories.Find(id);
			if (obj==null)
			{
				return NotFound();
			}

			obj.IsDeleted = true;
			_db.SaveChanges();
			TempData["success"] = "(Category successfully deleted!)";
			return RedirectToAction("Index");
			
		}



		//GET
		public IActionResult Edit(int? id)
		{
			if (id == null || id==0)
			{
				return NotFound();
			}

			Category? categoryFromDb = _db.Categories.FirstOrDefault(x=>x.CategoryId==id);
			if (categoryFromDb == null)
			{
				return NotFound();
			}

			return View(categoryFromDb);
		}

		[HttpPost]
		public IActionResult Edit(Category obj)
		{
            if (ModelState.IsValid)
            {
				_db.Categories.Update(obj);
				_db.SaveChanges();
				return RedirectToAction("Index");
            }
			return View(obj);
        }

		
	} 
}
		

ProductsModule/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProductsModule.Data;
using ProductsModule.Models;

namespace ProductsModule.Controllers
{
	public class CommentController : Controller
	{
		private readonly AppDbContext _db;
		public CommentController(AppDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{
			List<Comment> objCommentList = _db.Comment.Where(c=>!c.IsDeleted).ToList();
			return View(objCommentList);
		}

		public IActionResult Create()
		{
			IEnumerable<SelectListItem> CommentList = _db.Products.Where(c => !c.IsDeleted).ToList().Select(u => new SelectListItem
			{
				Text = u.Title,
				Value = u.Id.ToString()
			});

			ViewData["CommentList"] = CommentList;

			return View();
		}

		[HttpPost]
		public IActionResult Create(Comment obj, int ProductId)
		{
			var selectedProduct = _db.Products.FirstOrDefault(c=>c.Id == ProductId);
			
			obj.Product = selectedProduct;

			_db.Comment.Add(obj);
			_db.SaveChanges();
			TempData["success"] = "(Comment successfully created!)";
			return RedirectToAction("Index");

		}


		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			Comment? commentFromDb = _db.Comment.FirstOrDefault(x => x.Id == id);
			if (commentFromDb == null)
			{
				return NotFound();
			}

			return View(commentFromDb);
		}


		[HttpPost]
		[ActionName("Delete")]
		public IActionResult DeletePOST(int? id)
		{
			Comment? obj = _db.Comment.Find(id);
			if (obj == null)
			{
				return NotFound();
			}

			obj.IsDeleted = true;
			_db.SaveChanges();
			TempData["success"] = "(Comment successfully deleted!)";
			return RedirectToAction("Index");

		}

		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			Comment? commentFromDb = _db.Comment.FirstOrDefault(x => x.Id == id);
			if (commentFromDb == null)
			{
				return NotFound();
			}

			return View(commentFromDb);
		}

		[HttpPost]
		public IActionResult Edit(Comment obj, int ProductId)
		{
			var selectedProduct = _db.Products.FirstOrDefault(c => c.Id == ProductId);

			obj.Product = selectedProduct;

			_db.Comment.Update(obj);
			_db.SaveChanges();
			
			return RedirectToAction("Index");

		}


	}
}

ProductsModule/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProductsModule.Data;
using ProductsModule.Models;
using ProductsModule.Models.ViewModels;
using System.ComponentModel;

namespace ProductsModule.Controllers
{
	
	public class ProductController : Controller
	{
		private readonly AppDbContext _db;
		private readonly IWebHostEnvironment _webHostEnvironment;

		public ProductController(AppDbContext db, IWebHostEnvironment webHostEnvironment)
		{
			_db = db;
			_webHostEnvironment = webHostEnvironment;
		}
		public IActionResult Index(string searchString, int pageNumber)
		{
			ViewData["CurrentFilter"] = searchString;

			var query = _db.Products
			.Include(p => p.Categories)
			.Select(p => new ProductWithCategories
			{
				ProductId = p.Id,
				ProductName = p.Title,
				Description = p.Description,
				ImageUrl = p.ImageUrl,
				CreationDate = p.CreationDate,
				IsDeleted = p.IsDeleted,
				Categories = p.Categories.Select(c => c.Category).ToList()
			})
			.Where(b => !b.IsDeleted);

			//searching:
			
			if (!String.IsNullOrEmpty(searchString))
			{
				query = query.Where(p => p.ProductName.Contains(searchString));
			}

			//paging:
			int pageSize = 3;
			

			var productsWithCategories = query.ToList();

			return View(PageList<ProductWithCategories>.Create(productsWithCategories, pageNumber, pageSize));
		}

		public IActionResult Create()
		{

			ProductVM productVM = new ProductVM()
			{
				CategoryList = _db.Categories.Where(c=>!c.IsDeleted).ToList().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.CategoryId.ToString()
				}),
				Product = new Product()
			};
			
			return View(productVM);
		}

		[HttpPost]
		public IActionResult Create(ProductVM obj)
		{
			if (ModelState.IsValid)
			{
				if (obj.Product.SelectedCategoryId != null)
				{
					
					var selectedCategory = _db.Categories.Find(obj.Product.SelectedCategoryId);

					obj.Product.Categories = new List<ProductCategory> { new ProductCategory { CategoryCategoryId = obj.Product.SelectedCategoryId, Category = selectedCategory } };

					
					if (obj.ImageFile != null)
					{
						string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
						string fileName = Guid.NewGuid().ToString() + "_" + obj.ImageFile.FileName;
						string filePath = Path.Combine(uploadFolder, fileName);

						using (var fileStream = new FileStream(filePath, FileMode.Create))
						{
							obj.ImageFile.CopyTo(fileStream);
						}

						obj.Product.ImageUrl = "/images/" + fileName;
					}
					
					_db.Products.Add(obj.Product);
					_db.SaveChanges();
					TempData["success"] = "(Product successfully created!)";
						
					return RedirectToAction("Index");
				}
			}
			//jakby modelState był false to sprawdzam co jest nie tak:
			foreach (var modelStateKey in ModelState.Keys)
			{
				var modelStateVal = ModelState[modelStateKey];
				if (modelStateVal.Errors.Count > 0)
				{
					foreach (var error in modelStateVal.Errors)
					{
						Console.WriteLine($"Błąd walidacji dla {modelStateKey}: {error.ErrorMessage}");
					}
				}
			}
			obj.CategoryList = _db.Categories.Where(c => !c.IsDeleted).Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.CategoryId.ToString()
				}).ToList();

				return View(obj);
			

		}

		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			Product? productFromDb = _db.Products.FirstOrDefault(x => x.Id == id);
			if (productFromDb == null)
			{
				return NotFound();
			}

			return View(productFromDb);
		}

		[HttpPost]
		[ActionName("Delete")]
		public IActionResult DeletePOST(int? id)
		{
			Product? obj = _db.Products.Find(id);
			if (obj==null)
			{
				return NotFound();
			}
			obj.IsDeleted = true;
			_db.SaveChanges();
			TempData["success"] = "(Product successfully deleted!)";
			return RedirectToAction("Index");
		}


		//GET
		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var existingProduct = _db.Products.Include(p => p.Categories).FirstOrDefault(p => p.Id == id);
			ProductVM productVM = new ProductVM()
			{
				CategoryList = _db.Categories.Where(c => !c.IsDeleted).ToList().Select(u => new SelectListItem
				{
					Text = u.Name,
					Value = u.CategoryId.ToString()
				}),
				Product = _db.Products.FirstOrDefault(p=>p.Id==id),
		};
			

			if (productVM == null)
			{
				return NotFound();
			}

			return View(productVM);
		}

		[HttpPost]
		public IActionResult Edit(ProductVM obj)
		{
			if (ModelState.IsValid)
			{
				var existingProduct = _db.Products.Include(p => p.Categories).FirstOrDefault(p => p.Id == obj.Product.Id);

				existingProduct.Categories.Clear();

				if (obj.Product.SelectedCategoryId!=null) 
				{
					var selectedCategory = _db.Categories.Find(obj.Product.SelectedCategoryId);

					existingProduct.Categories.Add(new ProductCategory { CategoryCategoryId = obj.Product.SelectedCategoryId, Category = selectedCategory });
					existingProduct.Title=obj.Product.Title;
					existingProduct.Description = obj.Product.Description;
					
					existingProduct.CreationDate = obj.Product.CreationDate;

					if (obj.ImageFile != null)
					{
						string uploadFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
						string fileName = Guid.NewGuid().ToString() + "_" + obj.ImageFile.FileName;
						string filePath = Path.Combine(uploadFolder, fileName);

						using (var fileStream = new FileStream(filePath, FileMode.Create))
						{
							obj.ImageFile.CopyTo(fileStream);
						}

						obj.Product.ImageUrl = "/images/" + fileName;
						existingProduct.ImageUrl = obj.Product.ImageUrl;

					}
					
					_db.SaveChanges();
					return RedirectToAction("Index");
				}
				
			}

			obj.CategoryList = _db.Categories.Where(c => !c.IsDeleted).Select(u => new SelectListItem
			{
				Text = u.Name,
				Value = u.CategoryId.ToString()
			}).ToList();

			return View(obj);
		}

		public IActionResult Details(int id)
		{
			var productWithComments = _db.Products.Include(p=>p.Comments.Where(p => !p.IsDeleted)).FirstOrDefault(p=>p.Id == id);

            if (productWithComments == null)
			{
				return NotFound();
			}
            
			return View(productWithComments);

        }

		public IActionResult AddComment(int id) 
		{
			IEnumerable<SelectListItem> CommentList = _db.Products.Where(c => !c.IsDeleted).ToList().Select(u => new SelectListItem
			{
				Text = u.Title,
				Value = u.Id.ToString()
			});

			ViewData["CommentList"] = CommentList;

			return View();
		}

		[HttpPost]
		public IActionResult AddComment(Comment obj, int ProductId)
		{
			var selectedProduct = _db.Products.FirstOrDefault(c => c.Id == ProductId);

			obj.Product = selectedProduct;

			_db.Comment.Add(obj);
			_db.SaveChanges();
			TempData["success"] = "(Comment successfully created!)";
			return RedirectToAction("Index");

		}

	}
}

ProductsModule/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magic Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductsModule.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Magic Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Category list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Comment" asp-action="Index">User's comments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">Product list</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>



    <footer class="border-top footer bg-primary text-white">
        <div class="container">
            &copy; 2023 - Magic Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProductsModule/Views/Shared/_Notification.cshtml
@*partial view for notifications on all the pages*@

@if (TempData["success"] != null)
{
	<div class="container">
		<div class="row pt-4 pb-3">
			<div class="col-6">
				<div class="alert alert-success" role="alert"> @TempData["success"] </div>
			</div>
		</div>
	</div>
}

@if (TempData["error"] != null)
{
	<div class="container">
		<div class="row pt-4 pb-3">
			<div class="col-6">
				<div class="alert alert-danger" role="alert"> @TempData["error"] </div>
			</div>
		</div>
	</div>
}